### PR TITLE
Modify build.gradle such that shadowJar only produces 1 fat jar file

### PR DESCRIPTION
**Pull request by aureliony**
Fixes the issue described in #1

### CODE REVIEW

**Comment by damithc** [comment]
Thanks for this PR @aureliony 
Do we know anything about the implications? i.e., why such a line is needed, and what are we losing when we remove it?

**Comment by itstrueitstrueitsrealitsreal** [comment]
After experimenting with the `./gradlew distTar` and `./gradlew distZip`, I found out that they generate the `AB3-J17.jar` file, which is the one we do not want, and that is because that line states that the `shadowJar` depends on the `distTar` and `distZip` tasks to be completed, resulting in two `.jar` files being generated, both `duke.jar` (which can be run) and `duke-J17.jar` (which gives the error, `no main manifest attribute, in duke-J17.jar`). 

Screenshot 2024-07-17 at 2 02 06 PM

The `distTar` and `distZip` tasks are built in tasks as specified by gradle, which can be viewed by entering `./gradlew tasks --all`.

Removing the line allows only `duke.jar` to be generated, which is what we want.

However, running `./gradlew build` still results in both the files being generated, as it uses gradle's tasks instead of `shadowJar`.

Moving forward, we could place greater emphasis on asking the students to use the `.jar` file generated by `./gradlew shadowJar` instead of the one generated by `./gradlew build`, which generates 2 `.jar` files, which may be confusing for them.

**Comment by damithc** [comment]
Thanks for the PR, @aureliony 
As this is a non-trivial change, we need a detailed commit message with a body, following [this convention](https://se-education.org/guides/conventions/git.html). 
Example: https://github.com/nus-oss/AB3-J17/commit/ef75f680e27e348993a8e4adecb1c2822cebb889

**Comment by aureliony** [comment]
I have updated the commit to include a detailed message body.

**Comment by damithc** [comment]
> I have updated the commit to include a detailed message body.

Thanks @aureliony 
The new commit message has sufficient details. I reorganized the flow a bit, as follows. 
```
build.gradle: Prevent generating a second JAR file

In build.gradle, the dependencies on distZip and/or distTar causes
the shadowJar task to generate a second JAR file for which the
mainClass.set("seedu.duke.Duke") does not take effect.
Hence, this additional JAR file cannot be run.
For this product, there is no need to generate a second JAR file
to begin with.

Let's remove this dependency from the build.gradle to prevent the
the shadowJar task from generating the extra JAR file.
```
What do you think? Feel free to tweak further as you see fit.

**Comment by aureliony** [comment]
> > I have updated the commit to include a detailed message body.
> 
> Thanks @aureliony The new commit message has sufficient details. I reorganized the flow a bit, as follows.
> 
> ```
> build.gradle: Prevent generating a second JAR file
> 
> In build.gradle, the dependencies on distZip and/or distTar causes
> the shadowJar task to generate a second JAR file for which the
> mainClass.set("seedu.duke.Duke") does not take effect.
> Hence, this additional JAR file cannot be run.
> For this product, there is no need to generate a second JAR file
> to begin with.
> 
> Let's remove this dependency from the build.gradle to prevent the
> the shadowJar task from generating the extra JAR file.
> ```
> 
> What do you think? Feel free to tweak further as you see fit.

Sound good to me. Fixed the double `the` typo and updated.

**Review by damithc — APPROVED** [review]

**Pull request merged**
